### ISSUE TITLE
Possible Enhancement

### ISSUE THREAD

**Issue by jacobsmith** [Cosbgn/tailwindcss-tooltips#2]
Hi,

Thanks so much for sharing this! One thing I modified on my project was to change the specificity so I could continue to add additional classes after `tooltip` to further override styling. So,

```
.tooltip {
  @apply invisible p-4 absolute z-50 inline-block ml-4 text-sm rounded-lg bg-gray-700 text-white;
}

.has-tooltip:hover .tooltip {
    @apply visible;
}
```

And then use is like:

```
                    <div className="has-tooltip">
                          Hover me to see the tooltip
                          <div className="tooltip">I am the tooltip text</div>
                    </div>
```

This lets me do something like:

```
                    <div className="has-tooltip">
                          Hover me to see the tooltip
                          <div className="tooltip w-32 bg-red-500">I am the tooltip text</div>
                    </div>
```

And override classes inline for greater flexibility. I also removed the default width so that it would fit the content in the tooltip. I updated class names also to be a bit more clear with the way I'm utilizing it, but I'm not sure how "tailwind"-y they are.

Thanks again for sharing your solution - just wanted to drop this in case anyone else runs across a similar issue of needing to override classes.

**Comment by cosbgn** [comment]
Hi, 
I'm not sure I understand your question. With the settings as they are you can already add additional classes no?
From the read-me example: https://jsfiddle.net/xjnw5vdz/1/ you can see that there is `bg-yellow-400` after `tooltip`.

You can change that to anything.

As for the class name it's really up to you, I like `has-tooltip` it reminds me of bulma.css

**Comment by cosbgn** [comment]
Hi I just tested on play.tailwind.com and I understood what you mean. I've updated the code to reflect your enhancements. Thank you very much!

**Comment by jacobsmith** [comment]
👍 sure thing! Thanks for the great start, @Cosbgn !
